# Week2授業前課題3
【課題1】内積を手計算しよう
【課題2】1次元配列の内積をfor文で計算しよう
【課題3】多次元配列の内積をfor文で計算しよう
【課題4】内積をnp.dotで計算しよう
【課題5】内積ができないときはどうするか

## 【課題1】内積を手計算しよう
行列の内積A*Bを手計算で解きなさい。

## 【課題2】1次元配列の内積をfor文で計算しよう
ご自身で配列のindexを指定し、
行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる
行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる
行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる
それらの値を全て足し合わせる
のフローをfor文を使って計算してください。

In [1]:
import numpy as np

A = np.array(
    [
      [-1 ,2 ,3]
    , [4 ,-5 ,6]
    , [7 ,8 , -9]
    ]
)

B = np.array(
    [
      [0, 2, 1]
    , [0, 2, -8]
    , [2, 9, -1]
    ]
)

inner_product = []

for i in range(3):
    inner_product.append(A[0][i] * B[i][0])

sum(inner_product)

6

## 【課題3】多次元配列の内積をfor文で計算しよう
for文を使って行列A、Bの積を計算しましょう！【課題2】では(0,0)のみ計算していただきましたが、全て計算してください。

In [2]:
inner_product = []

for row in range(3):
    for column in range(3):
        inner_product_value = 0
        for i in range(3):
            inner_product_value += A[row][i] * B[i][column]
        inner_product.append(inner_product_value)

np.array(inner_product).reshape(3,3)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【課題4】内積をnp.dotで計算しよう
np.dot(A,B)と計算すると、【課題3】で計算していただいたことが一瞬でできます。
np.dot(A,B)を計算して、【課題3】と同じになることを試してください。

In [3]:
np.dot(A,B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【課題5】内積ができないときはどうするか
行列A*Bを計算しようとすると、エラーが出て計算できません。なぜエラーが出るのか理由を記載してください。
そして、行列A、Bのどちらかにある操作をするとエラーが出ずに計算できます。
自分である操作を施し、内積を計算してください。

In [4]:
# 行数2、列数3
A = np.array(
    [
          [-1, 2, 3]
        , [4, -5, 6]
    ]
)

# 行数2、列数3
B = np.array(
    [
          [-9, 8, 7]
        , [6, -5, 4]
    ]
)

# ここでエラーになるのは、内積を求める対象行列の行と列の数が揃っていないため。

# np.dot(A, B.T)
np.dot(A.T, B)

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])